Carnation/Controllers/MessageController.cs
using BusinessLayer.Interfaces;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using BusinessLayer.Enums;
using BusinessLayer;

namespace Carnation.Controllers
{
    [System.Web.Mvc.Authorize]
    public class MessageController : Controller
    {
        [Dependency]
        protected IMessageServices MessageServices { get; set; }

        [System.Web.Mvc.Authorize]
        // GET: Message
        public ActionResult Index()
        {
            return View();
        }

        [System.Web.Mvc.Authorize]
        public ActionResult MessageSend()
        {
            return View();
        }

        [System.Web.Mvc.Authorize]
        [HttpPost]
        public ActionResult SendMessage(string userId, string message)
        {
            var currentUserId = HttpContext.User.Identity.GetUserId();

            var result = MessageServices.SendMessage(userId, currentUserId, message);

            if (result.Response == MessageResponse.LimitReached)
            {
                return Json(new { success = false, resultText = "Limit reached today.Try tomorrow." });
            }
            if (result.Response == MessageResponse.Banned)
            {
                return Json(new { success = false, resultText = "You can't send message for this user. You're banned." });
            }

            if (result.Response == MessageResponse.Success)
            {
                //Ha sikeres az üzenet akkor SignalR segítségével ha éppen az üzeneteit olvassa a vevő fél tovább terjesztjük
                //SignalR context
                var context = GlobalHost.ConnectionManager.GetHubContext<TweetsHub>();
                //Felhasználó minden connectionId-ra továbbküldjük az üzenetet
                context.Clients.Group(userId).getMessage(result.Message);

                return Json(new { success = true });
            }
            return Json(new { });


        }

        [System.Web.Mvc.Authorize]
        public ActionResult GetTweets()
        {

            return View();
        }

        [System.Web.Mvc.Authorize]
        public ActionResult GetUserMessages()
        {
            var currentUserId = HttpContext.User.Identity.GetUserId();

            var model = MessageServices.GetUserMessages(currentUserId);
            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [System.Web.Mvc.Authorize]
        public ActionResult UpdateTweet(int tweetId, bool tweetStatus)
        {
            var status = MessageServices.UpdateTweet(tweetId, tweetStatus);

            if (status == TweetResponse.Success)
                return Json(new { success = true });

            return Json(new { success = false, errorMessage = "Can't update" });

        }
    }
}

Carnation/Controllers/UsersController.cs
using BusinessLayer.Interfaces;
using Microsoft.Practices.Unity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace Carnation.Controllers
{
    public class UsersController : Controller
    {
        [Dependency]
        protected IUserServices UserServices { get; set; }
        // GET: Users
        [Authorize]
        public ActionResult Index()
        {
            var currentUser = HttpContext.User.Identity.GetUserId();
            var model = UserServices.GetUserList(currentUser);
            return View(model);
        }

        public ActionResult ConfirmAccount()
        {
            return View("ConfirmAccount");
        }
        [Authorize]
        public ActionResult GetUserList()
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            var model = UserServices.GetUserList(currentUser);

            return Json(model.Users, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult Search(string selectedUser)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            var model = UserServices.SearchForUser(currentUser, selectedUser);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult SearchBan(string selectedUser)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            var model = UserServices.SearchForBanUser(currentUser, selectedUser);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult BanList()
        {
            return View();
        }

        [Authorize]
        public ActionResult AddBan(string userId)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            UserServices.AddBann(currentUser, userId);

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult RemoveBan(string userId)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            UserServices.RemoveBann(currentUser, userId);

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult GetBanList(string userId)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            var model = UserServices.GetBanList(currentUser);

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult GetVisibility()
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            var model = UserServices.GetVisibility(currentUser);

            return Json(new { visibility = model }, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        public ActionResult SetVisibility(bool visibility)
        {
            var currentUser = HttpContext.User.Identity.GetUserId();

            UserServices.SetVisibility(currentUser, visibility);

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
    }
}

Carnation/Views/Users/BanList.cshtml
@{
    ViewBag.Title = "BanList";
}
<script src="~/Scripts/ui-bootstrap-tpls-0.11.0.js"></script>
<script src="~/app/bannListApp.js"></script>

<h2>BanList</h2>
<div ng-app="bannApp">
    <div ng-controller="BanCtrl">
        <div class="form-group">
            <label for="userNames">Add to Bann list</label>
            <input type="text" ng-model="selectedUser" placeholder="Locations loaded via $http" typeahead="user as user.UserFullName for user in getUsers($viewValue) | filter:{name:$viewValue} | limitTo : 8" typeahead-loading="loadingLocations" class="form-control">
            <i ng-show="loadingLocations" class="glyphicon glyphicon-refresh"></i>
        </div>
        <div class="form-group">
            <button class="btn btn-primary" ng-click="addBann()">Add</button>
        </div>


        <table class="table table-striped">
            <tr>
                <th>
                    Username
                </th>
                <th>
                    Full name
                </th>
                <th>
                    Action
                </th>
            </tr>
            <tr ng-repeat="item in bannList">
                <td>{{item.UserName}}</td>
                <td>{{item.UserFullName}}</td>
                <td>
                    <button class="btn btn-danger" ng-click="removeBann(item.UserId)">Remove</button>
                </td>
            </tr>
        </table>
    </div>
</div>

Carnation/Views/Users/ConfirmAccount.cshtml
@{
    ViewBag.Title = "ConfirmAccount";
}

<h2>ConfirmAccount</h2>

<h3>Your account is ready. You get an email about it.Please confirm your account !</h3>

Carnation/Views/Users/Index.cshtml
@model BusinessLayer.ViewModels.UserListViewModel

@{
    ViewBag.Title = "Index";
}

<h2>User list</h2>

<div class="row">
    <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
        <ul class="event-list">
            @foreach (var item in Model.Users)
            {
                <li class="userItem">
                    <time datetime="2014-07-20">
                        <span class="day">@item.RegistrationDate.Day</span>
                        <span class="month">@item.RegistrationDate.Month</span>
                        <span class="year">@item.RegistrationDate.Year</span>
                    </time>
                    <img alt="AvatAR" src="http://img2.wikia.nocookie.net/__cb20130607025329/creepypasta/images/3/38/Avatar-blank.jpg" />
                    <div class="info">
                        <h2 class="title">@item.UserFullName</h2>
                        <p class="desc">@item.Email</p>
                        <p>
                            <button id="@item.UserId" class="openModal" data-username="@item.UserName">
                                Send Message
                            </button>
                        </p>
                    </div>
                    <div class="social">
                        <ul>
                            <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                            <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                            <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
                        </ul>
                    </div>
                </li>
            }

        </ul>

    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Send Mesage</h4>
            </div>
            <div class="modal-body">
                <div id="error" class="alert alert-danger" style="display:none"></div>
                <div id="success" class="alert alert-success" style="display:none">Message sent! :)</div>

                @using (Html.BeginForm("SendMessage", "Message", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input id="userId" hidden />

                    <div class="form-group">
                        <label for="userNames">User name</label>
                        <input type="text" class="form-control" id="userName" placeholder="UserName" disabled>
                    </div>

                    <div class="form-group">
                        <label for="message">Message</label>
                        <textarea id="message" class="form-control" placeholder="Text your message"></textarea>
                    </div>
                    <button type="button" class="btn btn-primary" id="sendMessage">Send message</button>
                }

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" id="closeModelButton">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
    $(function () {
        var error = $('#error');
        var success = $('#success');
        var message = $('#message');

        $('#closeModelButton').click(function () {
            error.hide();
            success.hide();
            message.val('');
        });
        $('.openModal').on("click", function () {
            var id = this.id;
            var name = $(this).data("username");

            $('#userId').val(id);
            $('#userName').val(name)
            $('#myModal').modal("show");
        });
        $('#sendMessage').click(function () {
            var userId = $('#userId').val();
            var message = $('#message').val();
            $.ajax({
                type: "POST",
                url: "/Message/SendMessage",
                data: { userId: userId, message: message },
            }).success(function (data) {
                if (data.success) {
                    success.show()
                    error.hide();
                    message.val('');
                }
                else {
                    error.append(data.resultText);
                    error.show();
                }
            }).fail(function (data) {
            });

        });
    });

</script>